### ISSUE TITLE
Skill Sorting - by Stat

### ISSUE THREAD

**Issue by drowzero0** [OctarineSourcerer/cyberpunk2020-foundry#45]
after implementing the Sort by function i noticed that the grouped skills do get mixed up within the special skills:

![image](https://user-images.githubusercontent.com/62395017/114673777-d8f17700-9d06-11eb-8e7f-b5d739279e29.png)

 i guess the groups need a stat reference to not get mixed in between the special skills.
 since it does an alphabetical sorting for each STAT, but SPECIAL + GROUPED.SKILL have no explicit STAT.

**Comment by OctarineSourcerer** [comment]
Happily, it wasn't them having a stat reference or not - it was that special was defined as having a sort index of 0, which because JS interprets 0 as false, the sort code was interpreting as "oh, that's not something I can give an order to" and gave them the same index as something without a stat.

Fixed in 50125ea, though I'd be happy to hear if there's a preferred stat sorting: at the moment, it's groups, specials, and then by stat in the same order the stats are currently listed on the sheet: int, ref, tech, cool, attr, luck, ma, bt, emp. I'm tempted to arrange both alphabetically.
